### ISSUE TITLE
.pth.tar problems

### ISSUE THREAD

**Issue by AndreaGimelli** [NeVerTools/NeVer2#12]
If i train a network, the program generates a .pth.tar (a training checkpoint). If I start a training with another network (a really new network with nothing in common with the previous network), the program continues to use the old .pht.tar saying that the "the checkpoint has been already reached"

**Comment by sdemarch** [comment]
Indeed it is due to the fact that the network is not saved yet. @darioguidotti should we force to save the current network before training or just delete the checkpoint if the network is volatile?

**Comment by GiacomoRosato** [comment]
no even if the network is already saved and there's a .pth.tar file of a different network gives the same issue
