### ISSUE TITLE
Program crash after verifying a network

### ISSUE THREAD

**Issue by AndreaGimelli** [NeVerTools/NeVer2#18]
The program crashes trying to verify a network with two generic SMT (1 Pre and 1 Post)![image_2021-09-09_15-26-11](https://user-images.githubusercontent.com/81355251/132694573-545174f1-a50c-49bf-a3b2-f93ba5253c05.png)
![image_2021-09-09_15-30-51](https://user-images.githubusercontent.com/81355251/132695057-853c358b-d287-4f5b-a597-e24b8f75c4ed.png)

**Comment by sdemarch** [comment]
Could you please attach the onnx and smtlib files? As far as I can see it should work, so I need to inspect in detail.

**Comment by GiacomoRosato** [comment]
[James.zip](https://github.com/NeVerTools/NeVer2/files/7137670/James.zip)

**Comment by sdemarch** [comment]
There is a weird behavior in pySMT API, both this repository and pyNeVer need to be updated. I will close this as soon as pyNeVer is updated.

**Comment by GiacomoRosato** [comment]
It returns a different error message in command line now.

![2021-09-10 16_06_16-](https://user-images.githubusercontent.com/81356558/132866450-72847482-1f9b-4ae6-8df3-9898fcacb7b1.png)
