### ISSUE TITLE
Unespected crash

### ISSUE THREAD

**Issue by AndreaGimelli** [NeVerTools/NeVer2#3]
A crash occurs when an unexpected character (for example a letter of the alphabet) fills some text fields.
For example: use a generic network, go to "train", -->"Dataset", -->"Custom data source", -->choose a data source,-->write a letter in the "target index" and the program will crash
<img width="418" alt="Schermata 2021-08-23 alle 11 15 26" src="https://user-images.githubusercontent.com/81355251/130422581-411ca098-5a1d-44e9-9bf3-bfe349d96c20.png">

**Comment by sdemarch** [comment]
QLineEdit validation

**Comment by sdemarch** [comment]
Note to self: data type should be a combo box with finite daa types.
